### PR TITLE
Empty table behaviour

### LINKED ISSUE #60: Empty table behaviour
Currently if there are no rows in the result the extractor doesn't do anything.

It is proposed that if there are no rows then the table in storage should be truncated (to match the source).

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #60 

proposed changes:

- always output a manifest
- write empty csv if for empty result set

### CODE REVIEW

**Comment by pivnicek** [comment]
There's an issue here: 
It normally writes the header to the csv file for the advanced query case, however if there are no results we don't know what the columns are.  So should it just write a blank csv in that case like it does for the simple table case?

**Comment by odinuv** [comment]
blank (0b) CSV file will definitivy cause an error, cause there is no way to import that. But even if there are no results, you can still get the tables of the query - sth like this https://stackoverflow.com/a/15671366/41640 ?

**Comment by pivnicek** [comment]
Yes, great (at least for PDO extractors). Thanks @odinuv

**Comment by pivnicek** [comment]
regarding blank csv files.  how should the no-rows case ideally behave do you think?  Just a manifest?

**Comment by odinuv** [comment]
i'd stick with https://github.com/keboola/docker-bundle/issues/323#issuecomment-396920876

**Comment by odinuv** [comment]
i'd stick with https://github.com/keboola/docker-bundle/issues/323#issuecomment-396920876

**Pull request closed without merging**
