### PR TITLE
allow overriding datatype metadata

### LINKED ISSUE #63: Allow Datatype Mapping Override
Sometimes types in one tech don't match basetypes in another (ex. MSSQL TIMESTAMP and BIT).
So this library should allow for components to define their own mappings.

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #63

### CODE REVIEW

**Comment by pivnicek** [comment]
Hmmm, I see your point, let me do a little refactor and see if it helps.  I just don't want to make any BC-break.

**Comment by MiroCillik** [comment]
Yeah, you're right about the BC. You can also leave a proxy function in the Extractor class.. But it's fine like this, just add the test :)

**Comment by pivnicek** [comment]
@MiroCillik Can you take another look at this please?  I'd like to merge if you agree.

**Comment by MiroCillik** [comment]
@pivnicek seems fine to me

**Comment by pivnicek** [comment]
Cheers! 🍻

**Comment by pivnicek** [comment]
@Actimel since this is a change to `9` that will need to get rebased onto `10`, please let me know if you want to change it in some way.

**Pull request merged**
